version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: adaptiserv-web
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1

  nginx:
    image: nginx:alpine
    container_name: adaptiserv-nginx
    restart: unless-stopped
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - ./certbot:/var/www/certbot:ro
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3

  certbot:
    image: certbot/certbot:latest
    container_name: adaptiserv-certbot
    depends_on:
      - nginx
    volumes:
      - ./certbot:/var/www/certbot:rw
      - ./ssl:/etc/letsencrypt:rw
    entrypoint: ["/bin/sh","-c"]
    command: "echo Certbot container ready. Use 'docker compose run --rm certbot certonly ...'"
